In [1]:
import contrans
import json
import pprint
import pandas as pd

In [2]:
contrans_obj = contrans.contrans()

In [3]:
bioguides = contrans_obj.get_bioguideIDs()
bioguides

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,L000397,18.0,"Lofgren, Zoe",Democratic,California,2024-10-22T14:54:19Z,https://api.congress.gov/v3/member/L000397?for...,Image courtesy of the Member,https://www.congress.gov/img/member/671024d7ec...,"[{'chamber': 'House of Representatives', 'star..."
1,L000604,4.0,"Lopez, Greg",Republican,Colorado,2024-10-10T21:25:00Z,https://api.congress.gov/v3/member/L000604?for...,Image courtesy of the Member,https://www.congress.gov/img/member/668e94fd65...,"[{'chamber': 'House of Representatives', 'star..."
2,M001225,15.0,"Mullin, Kevin",Democratic,California,2024-10-10T21:22:27Z,https://api.congress.gov/v3/member/M001225?for...,Image courtesy of the Member,https://www.congress.gov/img/member/m001225_20...,"[{'chamber': 'House of Representatives', 'star..."
3,M001229,10.0,"McIver, LaMonica",Democratic,New Jersey,2024-10-10T21:19:13Z,https://api.congress.gov/v3/member/M001229?for...,Image courtesy of the Member,https://www.congress.gov/img/member/66fd489d79...,"[{'chamber': 'House of Representatives', 'star..."
4,H001097,NaN,"Helmy, George S.",Democratic,New Jersey,2024-10-10T12:42:18Z,https://api.congress.gov/v3/member/H001097?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/6705445b99...,"[{'chamber': 'Senate', 'startYear': 2024}]"
...,...,...,...,...,...,...,...,...,...,...
534,B001267,NaN,"Bennet, Michael F.",Democratic,Colorado,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001267?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001267_20...,"[{'chamber': 'Senate', 'startYear': 2009}]"
535,B001243,NaN,"Blackburn, Marsha",Republican,Tennessee,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001243?for...,Image courtesy of the Member,https://www.congress.gov/img/member/b001243_20...,"[{'chamber': 'House of Representatives', 'endY..."
536,B001236,NaN,"Boozman, John",Republican,Arkansas,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001236?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001236_20...,"[{'chamber': 'House of Representatives', 'endY..."
537,B001230,NaN,"Baldwin, Tammy",Democratic,Wisconsin,2024-03-10T12:42:12Z,https://api.congress.gov/v3/member/B001230?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001230_20...,"[{'chamber': 'House of Representatives', 'endY..."
538,S001192,2.0,"Stewart, Chris",Republican,Utah,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,"[{'chamber': 'House of Representatives', 'endY..."

In [4]:
bioguides['lastname'] = [x.split(",")[0] for x in bioguides['name']]
bioguides['firstname'] = [x.split(",")[1] for x in bioguides['name']]

replace_map = {"Republican": "R",
               "Democratic": "D",
               "Independent": "I"}
bioguides['partyLetter'] = bioguides['partyName'].replace(replace_map)

bioguides['name2'] = [x + " " + y + " (" + z + ")" for x, y, z in zip(bioguides['firstname'], bioguides['lastname'], bioguides['partyLetter'])]
bioguides['name2']

0             Zoe Lofgren (D)
1              Greg Lopez (R)
2            Kevin Mullin (D)
3         LaMonica McIver (D)
4         George S. Helmy (D)
                ...
534     Michael F. Bennet (D)
535      Marsha Blackburn (R)
536          John Boozman (R)
537         Tammy Baldwin (D)
538         Chris Stewart (R)
Name: name2, Length: 539, dtype: object

In [5]:
# import requests
# r = requests.get(l[0]['url'], params = {"api_key": contrans_obj.congress_api_key})
# txt_url = json.loads(r.text)['bill']['textVersions']['url']
# r2 = requests.get(txt_url, params={"api_key": contrans_obj.congress_api_key})
# url_to_scrape = json.loads(r2.text)['textVersions'][0]['formats'][0]['url']

In [6]:
# from bs4 import BeautifulSoup

# html_doc = requests.get(url_to_scrape)
# gumbo = BeautifulSoup(html_doc.text, 'html.parser')
# print(type(gumbo))
# gumbo

In [7]:
# def get_bill_data(bill_url):
#     r = requests.get(bill_url, params = {"api_key": contrans_obj.congress_api_key})
#     txt_url = json.loads(r.text)['bill']['textVersions']['url']
#     r2 = requests.get(txt_url, params={"api_key": contrans_obj.congress_api_key})
#     url_to_scrape = json.loads(r2.text)['textVersions'][0]['formats'][0]['url']

#     html_doc = requests.get(url_to_scrape)
#     gumbo = BeautifulSoup(html_doc.text, 'html.parser') 
#     return gumbo

In [8]:
cands = pd.read_csv("data/cands22.txt", quotechar="|", header=None)
cands.columns = ['Cycle', 'FECCandID', 'CID','FirstLastP',
                 'Party','DistIDRunFor','DistIDCurr',
                 'CurrCand','CycleCand','CRPICO','RecipCode','NoPacs']
cands

,Cycle,FECCandID,CID,FirstLastP,Party,DistIDRunFor,DistIDCurr,CurrCand,CycleCand,CRPICO,RecipCode,NoPacs
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,
...,...,...,...,...,...,...,...,...,...,...,...,...
8923,2022,S8WI00224,N00041929,Leah Vukmir (R),R,WIS1,,,,,RN,
8924,2022,S8WV00119,N00041293,Paula Jean Swearengin (D),D,WVS2,,,,,DN,
8925,2022,S8WV00127,N00035531,Evan Jenkins (R),R,WVS1,,,,,RN,
8926,2022,S8WV00135,N00041474,Bo Copley (R),R,WVS1,,,,,RN,
8927,2022,S8WV00143,N00012642,Patrick Morrisey (R),R,WVS1,,,,,RN,

In [9]:
# want to join candidates table and the bioguides table
# what are we matching on, what kind of merge do we want? (One to one)
# What rows aren't matched and how to we fix
# crosswalk = pd.merge(bioguides, cands, 
#                      how='left', 
#                      left_on="name2", 
#                      right_on="FirstLastP",
#                      indicator = "matched",
#                      validate = "one_to_one"
#                      )
# crosswalk

In [10]:
members = contrans_obj.make_cand_table()

In [11]:
members['terms.item'][481]

[{'chamber': 'Senate', 'startYear': 2021}]

In [12]:
terms, members = contrans_obj.terms_df(members)

In [13]:
terms

                     chamber  startYear bioguideId  endYear
0   House of Representatives       1995    L000397      NaN
0   House of Representatives       2024    L000604      NaN
0   House of Representatives       2023    M001225      NaN
0   House of Representatives       2024    M001229      NaN
0                     Senate       2024    H001097      NaN
..                       ...        ...        ...      ...
0   House of Representatives       2001    B001236   2011.0
1                     Senate       2011    B001236      NaN
0   House of Representatives       1999    B001230   2013.0
1                     Senate       2013    B001230      NaN
0   House of Representatives       2013    S001192   2023.0

[594 rows x 4 columns]

In [14]:
members

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,partyletter,DistIDRunFor,lastname,firstname,name2,CID
0,L000397,18,"Lofgren, Zoe",Democratic,CA,2024-10-22T14:54:19Z,https://api.congress.gov/v3/member/L000397?for...,Image courtesy of the Member,https://www.congress.gov/img/member/671024d7ec...,D,CA18,Lofgren,Zoe,Lofgren (D),N00007479
1,L000604,04,"Lopez, Greg",Republican,CO,2024-10-10T21:25:00Z,https://api.congress.gov/v3/member/L000604?for...,Image courtesy of the Member,https://www.congress.gov/img/member/668e94fd65...,R,CO04,Lopez,Greg,Lopez (R),NaN
2,M001225,15,"Mullin, Kevin",Democratic,CA,2024-10-10T21:22:27Z,https://api.congress.gov/v3/member/M001225?for...,Image courtesy of the Member,https://www.congress.gov/img/member/m001225_20...,D,CA15,Mullin,Kevin,Mullin (D),N00049438
3,M001229,10,"McIver, LaMonica",Democratic,NJ,2024-10-10T21:19:13Z,https://api.congress.gov/v3/member/M001229?for...,Image courtesy of the Member,https://www.congress.gov/img/member/66fd489d79...,D,NJ10,McIver,LaMonica,McIver (D),NaN
4,H001097,S,"Helmy, George S.",Democratic,NJ,2024-10-10T12:42:18Z,https://api.congress.gov/v3/member/H001097?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/6705445b99...,D,NJS,Helmy,George S.,Helmy (D),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,B001267,S,"Bennet, Michael F.",Democratic,CO,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001267?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001267_20...,D,COS,Bennet,Michael F.,Bennet (D),N00030608
535,B001243,S,"Blackburn, Marsha",Republican,TN,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001243?for...,Image courtesy of the Member,https://www.congress.gov/img/member/b001243_20...,R,TNS,Blackburn,Marsha,Blackburn (R),N00003105
536,B001236,S,"Boozman, John",Republican,AR,2024-03-10T12:42:13Z,https://api.congress.gov/v3/member/B001236?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001236_20...,R,ARS,Boozman,John,Boozman (R),N00013873
537,B001230,S,"Baldwin, Tammy",Democratic,WI,2024-03-10T12:42:12Z,https://api.congress.gov/v3/member/B001230?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001230_20...,D,WIS,Baldwin,Tammy,Baldwin (D),N00004367
538,S001192,02,"Stewart, Chris",Republican,UT,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,R,UT02,Stewart,Chris,Stewart (R),N00033932

# Above

The above is now in first normal form.

In [15]:
votes = contrans_obj.get_ideology()

In [16]:
votes

,congress,chamber,icpsr,state_icpsr,district_code,state_abbrev,party_code,occupancy,last_means,bioname,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,118,House,20301,41,3,AL,200,NaN,NaN,"ROGERS, Mike Dennis",...,NaN,0.379,0.376,-161.36951,0.85666,1043.0,79.0,NaN,0.449,0.348
1,118,House,21102,41,7,AL,100,NaN,NaN,"SEWELL, Terri",...,NaN,-0.402,0.396,-51.44477,0.94995,1002.0,18.0,NaN,-0.524,0.368
2,118,House,21500,41,6,AL,200,NaN,NaN,"PALMER, Gary James",...,NaN,0.677,0.109,-88.04471,0.91949,1049.0,42.0,NaN,0.674,0.141
3,118,House,22108,41,1,AL,200,NaN,NaN,"CARL, Jerry L.",...,NaN,0.550,0.237,-124.31414,0.88973,1064.0,56.0,NaN,0.599,0.236
4,118,House,22140,41,2,AL,200,NaN,NaN,"MOORE, Barry",...,NaN,0.641,-0.247,-98.75167,0.91121,1062.0,42.0,NaN,0.715,-0.298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,118,House,21970,25,1,WI,200,NaN,NaN,"STEIL, Bryan",...,NaN,0.417,0.062,-116.72081,0.89583,1061.0,45.0,NaN,0.437,0.130
445,118,House,21989,25,7,WI,200,NaN,NaN,"TIFFANY, Thomas P.",...,NaN,0.641,-0.250,-91.17689,0.91713,1054.0,35.0,NaN,0.665,-0.286
446,118,House,22115,25,5,WI,200,NaN,NaN,"FITZGERALD, Scott",...,NaN,0.599,0.084,-99.09669,0.91091,1062.0,47.0,NaN,0.585,-0.013
447,118,House,22370,25,3,WI,200,NaN,NaN,"VAN ORDEN, Derrick",...,NaN,0.377,-0.014,-186.77268,0.83503,1036.0,84.0,NaN,0.376,-0.012
448,118,House,22325,68,1,WY,200,NaN,NaN,"HAGEMAN, Harriet",...,NaN,0.666,-0.354,-86.70007,0.92045,1046.0,36.0,NaN,0.664,-0.335

In [17]:
pw = contrans_obj.postgres_password
dbserver, engine = contrans_obj.connect_to_postgres(password=pw)

OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

In [21]:
import psycopg

user = "me"
password = contrans_obj.postgres_password
host = "localhost"
port = "5432"

dbserver = psycopg.connect(user=user, password=password, host=host, port=port)

OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

In [ ]:
members = contrans_obj.get_bioguideIDs()
members = contrans_obj.make_cand_table(members)
terms, members = contrans_obj.terms_df(members)
ideology = contrans_obj.get_ideology()
contrans_obj.make_members_df(members, ideology)